linkit_telephone.settings:
  type: config_object
  label: 'Linkit Telephone matcher settings'
  mapping:
    default_region_code:
      type: string
      label: 'Default region assumed for non-international number formats'